### PR TITLE
ClientAuth Cert Test

### PR DESCRIPTION
**Pull request by andrm**
Implemented a minimal test for client auth testing. Verification happens
in the ServerInterceptor. Works with grpc/netty.

### CODE REVIEW

**Comment by vietj** [comment]
can you show the netty/grpc client code that make it pass ?

**Comment by andrm** [comment]
Yes, this one works. Make sure you have unlimited jce policy enabled in your jre.

**Comment by andrm** [comment]
Sorry to nag, are there any plans for this? It would be great to have a fix soon.

**Comment by vietj** [comment]
we can try to  get it fixed for 3.5.1

**Comment by vietj** [comment]
I've implemented it with a few changes in Vert.x core to make it possible, we have actually to reconfigure the SSL engine from the SSL helper to have server configured for client auth

**Pull request closed without merging**
