### PR TITLE
[WIP] Issues/15 support for rxgrpc

### PR DESCRIPTION
**Pull request by rogelio-o**

### CODE REVIEW

**Comment by rogelio-o** [comment]
@vietj I’ve added the plugin and the updates to the original library to the PR. Tests of the original library are working with the stubs generated by the plugin.

@indiketa feel free to modify the code and create a PR to this branch, to propose things or to propose another way in which we can contribute.

**Comment by vietj** [comment]
have you signed the ECA @rogelio-o ?

**Comment by vietj** [comment]
the CI failed due to networking errors I triggered a new build

**Comment by vietj** [comment]
@rogelio-o the CI does not pass and the PR is not validated can you investigate ?

**Comment by rogelio-o** [comment]
> have you signed the ECA @rogelio-o ?

Yes

> @rogelio-o the CI does not pass and the PR is not validated can you investigate?

Sure! I'll take a look.

**Comment by rogelio-o** [comment]
@vietj, the tests errors are errors that also exist in the master branch (https://travis-ci.org/vert-x3/vertx-grpc/jobs/563626048). I was researching and I found that. I'm going to keep researching, just to warn.

**Comment by rogelio-o** [comment]
I've isolated the problem: SslTest fails and it doesn't close the server, so every test after also fails because of the server is already started. Ignoring SSLTest makes pass all tests.

**Comment by rogelio-o** [comment]
Solved adding dist trusty to travis CI.

**Pull request closed without merging**
