### PR TITLE
Use WriteStream when sending streams (in client and server)

### PR DESCRIPTION
**Pull request by indiketa**
I've implemented the proposed changes in:
https://github.com/vert-x3/vertx-grpc/issues/15#issuecomment-520788332

I think it's more clear and concise.

Before:

```
    startServer(new VertxStreamingGrpc.StreamingImplBase() {
      @Override
      public ReadStream<Item> pipe(ReadStream<Item> requestStream) {
        ManualReadStream<Item> responseStream = new ManualReadStream<>();

        requestStream
          .endHandler(v -> responseStream.end())
          .exceptionHandler(throwable -> responseStream.fail(throwable))
          .handler(responseStream::send);

        return responseStream;
      }
    });
```

After:

```
    startServer(new VertxStreamingGrpc.StreamingImplBase() {
      @Override
      public void pipe(ReadStream<Item> request, WriteStream<Item> response) {
        request.pipeTo(response);
      }
    });
```

### CODE REVIEW

**Comment by indiketa** [comment]
@vietj If you agree: 
- It's easy to remove the dependencies on salesforce's jprotoc: I can include into this PR.
- The interfaces `GrpcWriteStream` `GrpcUniExchange` `GrpcReadStream` `GrpcBidiExchange` and their implementations are not used anymore in vertx-grpc. Can we remove this classes?
- Futurize `VertxServer` class methods (implies the loss of fluent methods: start, stop, shutdown...)

**Comment by vietj** [comment]
@indiketa I think that @pmlopes can comment for `GrpcWriteStream`, etc...

for now I'm fine having dependencies on salesforce jprotoc, we can see later if we want to remove it judging by the pro and cons.

for futurizing I would rather also address this in a separate effort.

in short let's keep this effort focusing on having a new compiler that is easy to maintain.

**Comment by vietj** [comment]
it seems this PR goes beyond the comment in the discussion, it also changes the async unary model from returning a `Future` to using a `Promise`.

For streams I'm sure it's better to have this model, for singles I am not sure it's preferable to do that given that in Vert.x 4 most operation will return a Future

**Comment by indiketa** [comment]
@vietj  Ok for dependencies on jprotoc

The change from `Future` to `Promise` is for consistency with streaming methods, server implementations that responds with streams:
`serverStub.method(request, WriteStream response);`
`serverStub.method(request, Promise response);`

The signature is consistent. Let me know if you want me to revert it to
`Future<Response> serverStub.method(request);

**Comment by vietj** [comment]
I think that is something we need to discuss here

**Comment by vietj** [comment]
my personal opinion is that we should use `Future` as return type because that's what we are going to promise in Vert.x 4.

**Comment by pmlopes** [comment]
@indiketa the idea with the interfaces was to try to see if in the future we could make gRPC polyglot too, in turned out not. So they are not used anywhere else except generated code. Since this is a future breaking change for 4.0 (right)? I believe they can be removed.

Now if we stick to core interfaces (Future, Promise, ReadStream, WriteStream) perhaps the goal of making the API polyglot will be possible and even easier as those types are already possible to handle.

**Comment by indiketa** [comment]
My personal opinions are to use Promise because:
- Methods are a stub implementation not a _normal_ callable method. Developer will not call them directly, those methods will be called from `VertxServer`. Is like in `Verticle.start(Promise<Void> startFuture)`
- Having to fulfill a `Promise` to the client is more natural than return a `Future`.
- Consistency with streaming calls.

But, you are the project leader, your opinion has more weight than mine. 
What you decide is fine for me!

**Comment by vietj** [comment]
polyglot is a non goal.

our goals are:

- either they use plain gRPC and it works fine
- they are using Vert.x and embrace Vert.x types
- using vertx-rx should be possible as well which is not covered

**Comment by vietj** [comment]
@indiketa can you update the PR to have `Future` returned instead of `Promise` passed ?

**Comment by indiketa** [comment]
Of course! Here we go

**Comment by indiketa** [comment]
@vietj Done

**Comment by vietj** [comment]
thanks for the contrib in the contrib

**Pull request merged**
