### PR TITLE
Bump grpc from 1.44.0 to 1.47.0

### PR DESCRIPTION
**Pull request by yeikel**
Motivation:

Maintenance

### CODE REVIEW

**Comment by yeikel** [comment]
Note that GRPC just released 1.45.0 and I just updated this PR instead

**Comment by yeikel** [comment]
Note that the GRPC team just released 1.45.1 and I just updated this PR instead

**Comment by yeikel** [comment]
@pmlopes Could you please take a look at this?

**Comment by yeikel** [comment]
Note that the GRPC team just released 1.47.0 and I just updated this PR instead

**Comment by yeikel** [comment]
@pmlopes Could you please review this?

**Comment by yeikel** [comment]
> Which netty version does it use? We need to keep it aligned with core otherwise we had issues in the past.

[4.1.72.Final](https://github.com/grpc/grpc-java/blob/v1.47.x/repositories.bzl#L30)

**Comment by pmlopes** [comment]
We're on .77 and it seems that tests are still green, so it should be fine!

**Pull request merged**
