### PR TITLE
Upgrade to grpc-java 1.4.0

### PR DESCRIPTION
**Pull request by eikemeier**
See <https://github.com/vert-x3/vertx-grpc-java-compiler/pull/6>

### CODE REVIEW

**Comment by vietj** [comment]
thanks, before applying this, we should upgrade Netty to the same version in the stack

I will take care of this.

**Comment by vietj** [comment]
do you know if a new version of grpc is planned, this actual uses Netty 4.1.11 and I would like to use at least Netty 4.1.12 that has a feature for a vertx core issue

**Comment by vietj** [comment]
the current master version of grpc-java uses Netty 4.1.13 , perhaps we should wait until this is released I think

**Comment by eikemeier** [comment]
This should be done by dependency resolution:

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_resolution

Usually, when vertex core depends on netty 4.1.13.Final, it should win. Otherwise you can always force a version by depending implicitly on it. It is uncommon for all libraries to depend on the same version of external libraries, especially when they are not from the same provider.

**Pull request closed without merging**
