### PR TITLE
Bump guava

### PR DESCRIPTION
**Pull request by pmlopes**
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

Motivation:

Update guava dependency

### CODE REVIEW

**Comment by yeikel** [comment]
@pmlopes What is blocking this change?

**Comment by vietj** [comment]
@yeikel this change would need to be updated on the entire vertx stack which is a difficult upgrade.

**Comment by yeikel** [comment]
@vietj Unfortunately https://github.com/advisories/GHSA-5mg8-w23w-74h3 prevent me from using this plugin and upgrading would solve it for me

**Comment by pmlopes** [comment]
@yeikel we need to update the whole stack to align the version of guava, however, rest assured that gRPC does not use the mentioned method in question in the CVE, so it's not affecting your, except, creating false positive alerts.

**Comment by pmlopes** [comment]
To complete what @vietj wrote, when using multiple components from the vert.x stack, if versions are not aligned we end up with multiple guava versions on the classpath which will cause runtime issues. Upgrading wasn't trivial as some old guava versions are used and will break with 30. So, we need to figure out a way to align them all.

**Comment by yeikel** [comment]
@pmlopes Unfortunately, the scans are not permissive and cannot understand the usage of the impacted APIs in this library. We can't guarantee that it won't be used in the future so there is that issue as well. 

I understand the complexity of the upgrade. Is there anything I could do to help? 

I think that the best course of action is to upgrade to the latest version and use that in all the components. Do we have enough test coverage to support this upgrade?

**Comment by yeikel** [comment]
Another challenge that I forgot to mention is that the process to exclude dependencies is per version. In the next Vertx release, I will need to work with my team again to exclude 4.2.3 and so on

**Comment by yeikel** [comment]
Gson is another dependency that is problematic and in this case it seems to be a transitive dependency : 

https://github.com/salesforce/grpc-java-contrib/pull/171/files

**Comment by pmlopes** [comment]
@yeikel I'll try to upgrade guava for the whole stack in 4.3. Regarding gson, again it's a false positive as vertx json is all handled by Jackson.

**Comment by yeikel** [comment]
> @yeikel I'll try to upgrade guava for the whole stack in 4.3. Regarding gson, again it's a false positive as vertx json is all handled by Jackson.

Thank you! 

I understand that it is a false positive but it still shows up in scans. I pushed https://github.com/vert-x3/vertx-grpc/pull/108 to fix it

**Comment by pmlopes** [comment]
@yeikel I've updated guava across the stack to 30.1.1-jre (which should be CVE free)

**Comment by yeikel** [comment]
> @yeikel I've updated guava across the stack to 30.1.1-jre (which should be CVE free)

Thank you for your help!

**Pull request closed without merging**
